# Generated by Django 5.1.4 on 2024-12-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snackshop', '0002_remove_product_flavor_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
