# Generated by Django 5.1.4 on 2024-12-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snackshop', '0007_product_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('chips', 'Chips'), ('cookies', 'Cookies'), ('jerky', 'Jerky'), ('bars', 'Bars'), ('nuts', 'Nuts & Trail Mix'), ('soda', 'Soda'), ('energy_drink', 'Energy Drink'), ('juice', 'Juice')], max_length=50, null=True),
        ),
    ]
