# Generated by Django 5.1.3 on 2024-12-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snackshop', '0008_alter_product_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('snack', 'Snack'), ('drink', 'Drink')], max_length=5, null=True),
        ),
    ]
