# Generated by Django 5.1.4 on 2025-01-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snackshop', '0018_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waiting for payment', 'Waiting for Payment'), ('shipped', 'Shipped'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
