# Generated by Django 5.1.4 on 2025-01-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snackshop', '0024_order_address_order_city_order_phone_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
